// import "./globals.css";

import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import { ThemeProvider } from "@/context/ThemeContext";
import Navbar from "./components/navbar/Navbar";
import "../styles//main.scss";
import { AnimatePresence } from "framer-motion";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <ThemeProvider>
          <Navbar />
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
